version: '3.5'
services:

  livegroup_api_server_container:
    container_name: livegroup_server
    ports:
      - "1337:1337"
    command: "sails lift"
    volumes:
      - './server:/usr/src/app'
      - '/usr/src/app/node_modules'
    build: ./server/
    depends_on:
      - livegroup_database_mongo
    links:
      - livegroup_database_mongo:livegroup_database_mongo

  livegroup_database_mongo:
    container_name: livegroup_database
    image: mongo
    ports:
      - "27017:27017"

  livegroup_api_client_container:
    container_name: livegroup_client
    ports:
      - "3000:3000"
    command: "npm start"
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    build: ./client/
    depends_on:
      - livegroup_api_server_container
    environment:
        - NODE_ENV=development
    links:
      - livegroup_api_server_container
