version: '3'
services:

  livegroup_backend:
    container_name: livegroup_backend
    image: livegroup_server
    build: ./server/
    command: sails lift
    ports:
      - "1337:1337"
    volumes:
      - './server:/app'
      - '/app/node_modules'
    depends_on:
      - livegroup_database
    networks:
      - livegroup_network

  livegroup_database:
    container_name: livegroup-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "livegroup_database:/data/db"
    networks:
      - livegroup_network

  livegroup_frontend:
    container_name: livegroup_frontend
    image: livegroup_client
    build: ./client/
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - './client:/app'
      - '/app/node_modules'
    depends_on:
      - livegroup_backend
      - livegroup_database
    networks:
      - livegroup_network

networks:
  livegroup_network:

volumes:
  livegroup_database:
    driver: local
