livegroup_api_server_container:

  container_name: livegroup_server
  ports:
    - "1337:1337"
  command: "sails lift"
  volumes:
    - ".:/usr/src/app"
    - '/usr/src/app/node_modules'
  build: .
  links:
    - livegroup_database_mongo:livegroup_database_mongo

livegroup_database_mongo:
  container_name: livegroup_database
  image: mongo
  ports:
    - "27017:27017"
